site_name: Notes
theme:
  name: readthedocs


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

plugins:
  - search

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js