site_name: Notes

repo_url: https://github.com/Indigo5684/Notes
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.footer
    - content.action.edit
    - content.action.view

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - git-authors

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css